# Site settings
title: Stefano Carli
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  Un informatico senza olio di palma.

url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

baseurl: / # the subpath of your site, e.g. /blog/
domain_name: 'http://stefanocarli.me'

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


